version: "3"
services:
  bot:
    container_name: bot
    build: .
    volumes:
      - .:/code
    env_file: .environment
    command: python3 bot.py
    depends_on:
      - db
  db:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "5432:5432"
