version: "3.4"
services:
  bot:
    container_name: bot
    build:
      context: .
      target: dev_build
    volumes:
      - .:/code
    env_file: .environment
    command: python3 bot.py
    depends_on:
      - db
  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
