version: "3"
services:
  bot:
    container_name: bot
    build: .
    env_file: .environment_prod
    command: python3 bot.py
    volumes:
      - /home/telegram-bookshelf-bot/logs:/code/logs
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/telegram-bookshelf-bot/database:/var/lib/postgresql/data
    ports:
      - "54333:5432"
